spring:
  mail:
    host: smtp.exmail.qq.com
    username: huangzhiwen@xiaoyujia.com
    password: aA215063628
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  freemarker:
    template-loader-path:
      - classpath:/templates
    suffix: .ftl
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

server:
  port: 2150
